---
#=========================
#   Policies - Variables
#=========================
intersight:
  policies:
    addons:
      - install_strategy: Always
        name: ccp-monitor
        upgrade_strategy: ReinstallOnFailure
      - install_strategy: Always
        name: kubernetes-dashboard
        upgrade_strategy: ReinstallOnFailure
      - chart_name: smm
        chart_version: 1.8.2-cisco2-helm3
        install_strategy: Always
        overrides:
          - demoApplication
          - enabled
          - true
        name: smm1_8
        release_name: smm1.8
        upgrade_strategy: ReinstallOnFailure
    kubernetes_version:
      - name: v1.20.14
        version: v1.20.14
      - name: v1.21.10
        version: v1.21.10
    network_cidr:
      - cni_type: Calico
        name: Asgard_CIDR
        pod_network_cidr: 100.71.0.0/16
        service_cidr: 100.72.0.0/16
    nodeos_configuration:
      - dns_servers:
          - 10.101.128.15
          - 10.101.128.16
        dns_suffix: rich.ciscolabs.com
        name: Asgard
        ntp_servers:
          - 10.101.128.15
          - 10.101.128.16
        timezone: America/New_York
    virtual_machine_infra_config:
      - description: Asgard vCenter
        name: Asgard
        target: asgard-vcenter.rich.ciscolabs.com
        virtual_infrastructure:
          - cluster: LOKI
            datastore: mjolnir
            interfaces:
              - prod|nets|10.92.112.0
            type: vmware
    virtual_machine_instance_type:
      - name: Small
      - cpu: 8
        name: Medium
        memory: 24576
        system_disk_size: 60
      - cpu: 12
        name: Large
        memory: 32768
        system_disk_size: 80
